<?php
/**
 * CAPTCHA Integration
 *
 * Unified CAPTCHA system supporting:
 * - Google reCAPTCHA v2 (Checkbox)
 * - Google reCAPTCHA v3 (Invisible)
 * - hCaptcha
 * - Cloudflare Turnstile
 *
 * @package Hikmah_Login
 * @subpackage Security
 * @since   1.0.0
 */

namespace Hikmah_Login\Security;

use Hikmah_Login\Traits\Singleton;
use Hikmah_Login\Traits\Hooks;
use Hikmah_Login\Helpers\Helper;
use Hikmah_Login\Helpers\Error_Handler;

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

class Captcha {

    use Singleton;
    use Hooks;

    /**
     * Supported CAPTCHA providers.
     */
    const PROVIDERS = [
        'recaptcha_v2' => 'Google reCAPTCHA v2',
        'recaptcha_v3' => 'Google reCAPTCHA v3',
        'hcaptcha'     => 'hCaptcha',
        'turnstile'    => 'Cloudflare Turnstile',
    ];

    /**
     * Verification API endpoints.
     */
    const VERIFY_URLS = [
        'recaptcha_v2' => 'https://www.google.com/recaptcha/api/siteverify',
        'recaptcha_v3' => 'https://www.google.com/recaptcha/api/siteverify',
        'hcaptcha'     => 'https://api.hcaptcha.com/siteverify',
        'turnstile'    => 'https://challenges.cloudflare.com/turnstile/v0/siteverify',
    ];

    /**
     * Constructor.
     *
     * The provider script is enqueued by the Assets module
     * (so it can be loaded only on Hikmah pages/shortcodes);
     * this class owns rendering + verification.
     */
    private function __construct() {

        if ( ! Helper::is_feature_enabled( 'captcha_enabled' ) ) {
            return;
        }

        $this->add_action( 'hikmah_login_form_bottom', 'render_captcha_field' );
        $this->add_action( 'hikmah_register_form_bottom', 'render_captcha_field' );
        $this->add_action( 'hikmah_forgot_password_form_bottom', 'render_captcha_field' );
    }

    /**
     * =============================================
     * RENDER CAPTCHA FIELD
     * =============================================
     */

    /**
     * Render the CAPTCHA widget in forms.
     *
     * @param string $form_id Form ID.
     */
    public function render_captcha_field( $form_id = '' ) {

        $type     = get_option( 'hikmah_captcha_type', 'recaptcha_v2' );
        $site_key = get_option( 'hikmah_recaptcha_site_key', '' );
        $theme    = get_option( 'hikmah_captcha_theme', 'light' );
        $input_id = $form_id ? $form_id . '-captcha' : 'hikmah-captcha';

        if ( empty( $site_key ) ) {
            return;
        }

        echo '<div class="hikmah-field hikmah-captcha-field">';

        switch ( $type ) {

            case 'recaptcha_v2':
                printf(
                    '<div class="g-recaptcha" data-sitekey="%s" data-theme="%s" data-callback="hikmahRecaptchaCallback" data-expired-callback="hikmahRecaptchaExpired"></div>',
                    esc_attr( $site_key ),
                    esc_attr( $theme )
                );
                break;

            case 'recaptcha_v3':
                // v3 is invisible — the token is generated by JS.
                printf(
                    '<input type="hidden" name="captcha_response" class="hikmah-recaptcha-v3-response hikmah-captcha-response" id="%s" data-sitekey="%s">',
                    esc_attr( $input_id ),
                    esc_attr( $site_key )
                );
                break;

            case 'hcaptcha':
                printf(
                    '<div class="h-captcha" data-sitekey="%s" data-theme="%s" data-callback="hikmahRecaptchaCallback"></div>',
                    esc_attr( $site_key ),
                    esc_attr( $theme )
                );
                break;

            case 'turnstile':
                printf(
                    '<div class="cf-turnstile" data-sitekey="%s" data-theme="%s" data-callback="hikmahTurnstileCallback"></div>',
                    esc_attr( $site_key ),
                    esc_attr( $theme )
                );
                break;
        }

        printf(
            '<input type="hidden" name="captcha_response" id="%s" class="hikmah-captcha-response">',
            esc_attr( $input_id )
        );
        echo '<span class="hikmah-field-error" data-field="captcha"></span>';
        echo '</div>';
    }

    /**
     * =============================================
     * VERIFICATION
     * =============================================
     */

    /**
     * Verify a CAPTCHA response.
     *
     * @param string $response CAPTCHA response token from frontend.
     * @return bool|\WP_Error True on success, WP_Error on failure.
     */
    public function verify( $response ) {

        if ( ! Helper::is_feature_enabled( 'captcha_enabled' ) ) {
            return true; // CAPTCHA disabled, skip
        }

        $type       = get_option( 'hikmah_captcha_type', 'recaptcha_v2' );
        $secret_key = get_option( 'hikmah_recaptcha_secret_key', '' );

        if ( empty( $secret_key ) ) {
            return true; // No secret configured, skip
        }

        if ( empty( $response ) ) {
            return new \WP_Error(
                'captcha_empty',
                __( 'Please complete the CAPTCHA verification.', 'hikmah-login' )
            );
        }

        $verify_url = self::VERIFY_URLS[ $type ] ?? '';

        if ( empty( $verify_url ) ) {
            return new \WP_Error( 'captcha_config', __( 'Invalid CAPTCHA configuration.', 'hikmah-login' ) );
        }

        // Make API request
        $api_response = wp_remote_post( $verify_url, [
            'body'    => [
                'secret'   => $secret_key,
                'response' => $response,
                'remoteip' => Helper::get_client_ip(),
            ],
            'timeout' => 10,
        ] );

        if ( is_wp_error( $api_response ) ) {
            Error_Handler::error( 'CAPTCHA API error: ' . $api_response->get_error_message() );
            return new \WP_Error(
                'captcha_api',
                __( 'CAPTCHA verification service unavailable.', 'hikmah-login' )
            );
        }

        $body = json_decode( wp_remote_retrieve_body( $api_response ), true );

        if ( ! $body || empty( $body['success'] ) ) {
            $error_codes = $body['error-codes'] ?? [];
            Error_Handler::warning( 'CAPTCHA failed: ' . implode( ', ', $error_codes ) );

            return new \WP_Error(
                'captcha_failed',
                __( 'CAPTCHA verification failed. Please try again.', 'hikmah-login' )
            );
        }

        // reCAPTCHA v3: Check score
        if ( 'recaptcha_v3' === $type ) {
            $min_score = (float) get_option( 'hikmah_recaptcha_min_score', 0.5 );
            $score     = isset( $body['score'] ) ? (float) $body['score'] : 0;

            if ( $score < $min_score ) {
                Error_Handler::warning( "reCAPTCHA v3 score too low: {$score} (min: {$min_score})" );
                return new \WP_Error(
                    'captcha_score',
                    __( 'CAPTCHA verification failed.', 'hikmah-login' )
                );
            }
        }

        return true;
    }

    /**
     * =============================================
     * ADMIN SETTINGS HELPERS
     * =============================================
     */

    /**
     * Get available providers for admin dropdown.
     *
     * @return array
     */
    public static function get_providers() {
        return self::PROVIDERS;
    }

    /**
     * Validate CAPTCHA settings.
     *
     * @param string $type       Provider type.
     * @param string $site_key   Site key.
     * @param string $secret_key Secret key.
     * @return array Validation errors (empty if valid).
     */
    public static function validate_settings( $type, $site_key, $secret_key ) {

        $errors = [];

        if ( ! array_key_exists( $type, self::PROVIDERS ) ) {
            $errors[] = __( 'Invalid CAPTCHA provider.', 'hikmah-login' );
        }

        if ( empty( $site_key ) ) {
            $errors[] = __( 'Site key is required.', 'hikmah-login' );
        }

        if ( empty( $secret_key ) ) {
            $errors[] = __( 'Secret key is required.', 'hikmah-login' );
        }

        return $errors;
    }
}